apiVersion: v1
kind: Namespace
metadata:
  name: drawio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: draw-letsencrypt-log
  namespace: drawio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: draw-letsencrypt-etc
  namespace: drawio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: draw-letsencrypt-lib
  namespace: drawio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw
  namespace: drawio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draw
  template:
    metadata:
      labels:
        app: draw
    spec:
      containers:
        - name: draw
          image: jgraph/drawio
          env:
            - name: LETS_ENCRYPT_ENABLED
              value: "true"
            - name: PUBLIC_DNS
              value: "localhost"
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 80
              name: http
            - containerPort: 8443
              name: https-internal
          volumeMounts:
            - name: letsencrypt-log
              mountPath: /var/log/letsencrypt
            - name: letsencrypt-etc
              mountPath: /etc/letsencrypt
            - name: letsencrypt-lib
              mountPath: /var/lib/letsencrypt
      volumes:
        - name: letsencrypt-log
          persistentVolumeClaim:
            claimName: draw-letsencrypt-log
        - name: letsencrypt-etc
          persistentVolumeClaim:
            claimName: draw-letsencrypt-etc
        - name: letsencrypt-lib
          persistentVolumeClaim:
            claimName: draw-letsencrypt-lib
---
apiVersion: v1
kind: Service
metadata:
  name: draw
  namespace: drawio
spec:
  selector:
    app: draw
  type: LoadBalancer
  ports:
    - name: http
      port: 87
      targetPort: 80
    - name: https
      port: 447
      targetPort: 844

